// Generated by dojo-bindgen on Tue, 4 Feb 2025 21:50:16 +0000. Do not modify this file manually.
using System;
using System.Threading.Tasks;
using Dojo;
using Dojo.Starknet;
using UnityEngine;
using dojo_bindings;
using System.Collections.Generic;
using System.Linq;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;

// System definitions for `city_builder-building_system` contract
public class Building_system : MonoBehaviour {
    // The address of this contract
    public string contractAddress;

    
    // Call the `place_building` system with the specified Account and calldata
    // Returns the transaction hash. Use `WaitForTransaction` to wait for the transaction to be confirmed.
    public async Task<FieldElement> place_building(Account account, uint x, uint y, uint building_type, uint residents, uint jobs, uint shopping_space, uint rotation) {
        List<dojo.FieldElement> calldata = new List<dojo.FieldElement>();
        calldata.Add(new FieldElement(x).Inner);
		calldata.Add(new FieldElement(y).Inner);
		calldata.Add(new FieldElement(building_type).Inner);
		calldata.Add(new FieldElement(residents).Inner);
		calldata.Add(new FieldElement(jobs).Inner);
		calldata.Add(new FieldElement(shopping_space).Inner);
		calldata.Add(new FieldElement(rotation).Inner);

        return await account.ExecuteRaw(new dojo.Call[] {
            new dojo.Call{
                to = new FieldElement(contractAddress).Inner,
                selector = "place_building",
                calldata = calldata.ToArray()
            }
        });
    }
            

    
    // Call the `upgrade` system with the specified Account and calldata
    // Returns the transaction hash. Use `WaitForTransaction` to wait for the transaction to be confirmed.
    public async Task<FieldElement> upgrade(Account account, FieldElement new_class_hash) {
        List<dojo.FieldElement> calldata = new List<dojo.FieldElement>();
        calldata.Add(new_class_hash.Inner);

        return await account.ExecuteRaw(new dojo.Call[] {
            new dojo.Call{
                to = new FieldElement(contractAddress).Inner,
                selector = "upgrade",
                calldata = calldata.ToArray()
            }
        });
    }
            
}
        