// Generated by dojo-bindgen on Fri, 24 Jan 2025 19:40:19 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;

// Type definition for `city_builder::models::BuildingType` enum
public abstract record BuildingType() : Enum {
    public record Residential() : BuildingType;
    public record Commercial() : BuildingType;
    public record Industrial() : BuildingType;
}


// Model definition for `city_builder::models::Building` model
public class city_builder_Building : ModelInstance {
    [ModelField("player")]
        public FieldElement player;

        [ModelField("x")]
        public uint x;

        [ModelField("y")]
        public uint y;

        [ModelField("building_type")]
        public BuildingType building_type;

        [ModelField("residents")]
        public uint residents;

        [ModelField("jobs")]
        public uint jobs;

        [ModelField("shopping_space")]
        public uint shopping_space;

        [ModelField("happy_residents")]
        public uint happy_residents;

        [ModelField("rotation")]
        public uint rotation;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        