// Generated by dojo-bindgen on Fri, 15 Nov 2024 01:52:45 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;


// Model definition for `city_builder::models::Tile` model
public class city_builder_Tile : ModelInstance {
    [ModelField("player")]
        public FieldElement player;

        [ModelField("x")]
        public uint x;

        [ModelField("y")]
        public uint y;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        