// Generated by dojo-bindgen on Tue, 4 Feb 2025 21:50:16 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;


// Model definition for `city_builder::models::Building` model
public class city_builder_Building : ModelInstance {
    [ModelField("player")]
        public FieldElement player;

        [ModelField("x")]
        public uint x;

        [ModelField("y")]
        public uint y;

        [ModelField("building_type")]
        public uint building_type;

        [ModelField("residents")]
        public uint residents;

        [ModelField("jobs")]
        public uint jobs;

        [ModelField("shopping_space")]
        public uint shopping_space;

        [ModelField("happy_residents")]
        public uint happy_residents;

        [ModelField("rotation")]
        public uint rotation;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        