// Generated by dojo-bindgen on Tue, 4 Feb 2025 21:50:16 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;


// Model definition for `city_builder::models::Player` model
public class city_builder_Player : ModelInstance {
    [ModelField("player")]
        public FieldElement player;

        [ModelField("money")]
        public BigInteger money;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        