[world]
name = "city-builder"
description = "On-chain city builder game"
seed = "city_builder"

[env]
rpc_url = "https://api.cartridge.gg/x/my-city-builder/katana"
account_address = "0x5b6b8189bb580f0df1e6d6bec509ff0d6c9be7365d10627e0cf222ec1b47a71"
private_key = "0x33003003001800009900180300d206308b0070db00121318d17b5e6262150b"

[namespace]
default = "city_builder"

[writers]
"city_builder-Building" = ["city_builder-building_system"]
"city_builder-Tile" = ["city_builder-tile_system"]
"city_builder-Player" = ["city_builder-player_system"]