[package]
cairo-version = "=2.8.4"
name = "city_builder"
version = "0.1.0"
edition = "2024_07"

[[target.starknet-contract]]
sierra = true
casm = true
build-external-contracts = ["dojo::world::world_contract::world"]

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo.git", tag = "v1.0.0" }
starknet = "2.8.4"

[scripts]
build = "sozo build"
migrate = "sozo migrate"
auth = "./scripts/default_auth.sh"
test = "sozo test"

[tool.dojo]
initializer = "src/lib.cairo"

[tool.dojo.env]
rpc_url = "https://api.cartridge.gg/x/my-city-builder/katana"
account_address = "0x0127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"